SUSE/doc-susemanager

xml/manager_reference_virtualization.xml
This is for 2.1 - is this the correct branch?
It should go to doc for 3.0 as well, but it seems the file with corresponding contents doesn't exist (was looking in the develop branch).
=> 2.1: Note about automatic populating of the self_update parameter in the Kerner Options

xml/public-cloud-setup.xml
The setup of the hostname is an important task prior to the yast based susemanager setup. The instructions how to setup the hostname were updated with regards to the required DNS update in the private network environment of the cloud provider
=> Update hostname setup instructions

xml/bp_chap_salt_minion_onboarding_scaleability.xml
From the mailing list:
> On 11/11/2016 15:45, Simon Crute wrote:
> Thanks,
> Although I think the command they suggest will only work if you have numbered minions.
> This might be a better one.
> 
> for k in $(salt-key -l un|grep -v Unaccepted); do salt-key -y -a $k; sleep 15; done
=> Suggest better command for minion onboarding

xml/bp_chap_salt_minion_onboarding_scaleability.xml
Recent Manager builds can onboard hundreds of minions at once without problems. This section can be removed.
=> BP: onboarding rate not a problem anymore

adoc/advanced_topics_virtualization.adoc
In the case the user just wants to restart VMs, stop them, etc,
it is not needed to register them.
=> Lower requirements for virt guests management.

adoc/advanced_topics_virtualization.adoc, adoc/bp_chap_troubleshooting.adoc
This PR makes the following changes in the documentation:
- Add notes about how to enable a Salt client as "Virtualization Host"
- Remove deprecated steps (from traditional clients) in "Registering a Cloned Salt Minion with SUSE Manager"
This changes has been suggested as outcome of this: https://github.com/SUSE/spacewalk/issues/4192
=> Add some documentation for enabling Salt Virtualization Hosts

adoc/quickstart3_chap_install_overview.adoc
@0rnela synced RES 6.9, and it required ~230GB.
=> Change diskspace requirement for RES from 200 to 250GB

adoc/quickstart3_chap_suma_keys_and_first_client.adoc
* In GS, no need to talk about non-systemd systems
* The menu is now call Salt[Keys]
=> no need to mention non-systemd; fix menu

adoc/entities.adoc
The documentation team tries to avoid camelCASE as much as possible
=> "Web UI" instead of "WebUI"

adoc/bp_sp_migration.adoc
Migration instructions in the BP Migration chapter only had migration from 3.0 to 3.1. Updated to reflect migration from 3.1 to 3.2. Reported by customer at https://bugzilla.suse.com/show_bug.cgi?id=1099348
=> Updated migration instructions from 3.1 to 3.2

adoc/entities.adoc, adoc/quickstart3_chap_install_overview.adoc
Also replaced the space between the number and the unit with non-breaking spaces ("4 GB" becomes "4{nbsp}GB").
=> Issue #4918 added new table to split out PPC requirements

adoc/quickstart3_chap_suma_setup_with_yast.adoc
Instead of two terms (address and URL) use a single one.  Maybe, link would be ok (it's a third one, though).
=> Unify terminology and simplify wording

adoc/command-line-tools.adoc
@keichwa reported:
> 'make suma-html' in develop fails for me with:
> 
> /ssd180/ke/github/doc-susemanager/build/.profiled/noprofile/MAIN-manager.xml:20165:32: error: value of attribute "numeration" is invalid; must be equal to "arabic", "loweralpha", "lowerroman", "upperalpha" or "upperroman"
> /usr/share/daps/make/validate.mk:40: recipe for target '/ssd180/ke/github/doc-susemanager/build/.profiled/noprofile/.validate' failed
> 
> 
> In MAIN-manager.xml I see:
> 
> <orderedlist numeration="NOTE">
> 
> Not sure whether that's the cause of the trouble and how it ended up
> there at all.  Can you repo it?
The error, in line 20165 of the generated XML file, can be traced back to the adoc file command-line-tools, on line 966, which had a malformed title on an admonition. This patch fixes that …
=> fixing build error

adoc/reference-webui-configuration.adoc
These are not allowed anymore because they cause problem in salt (salt interprets `.` as a separator character).
@jcayouette This change should go to 3.2 documentation. I created a PR against `develop` - is that correct or should I have used another branch?
=> Forbid dot characters in the configuration channels label

adoc/common_intro_feedback_i.adoc
@chabowski reported outdated feedback info:
* feedback page no longer exists
* new feedback address (doc-team@suse.com)
=> update feedback info; reported by Meike

adoc/advanced_topics_image_management.adoc
Add a tiny note about activation keys and image building.
=> Fix: specify which AK can be used when image building

adoc/quickstart3_chap_suma_keys_and_first_client.adoc
I like to propose to remove old or confusing admonitions.  command line tools are not subject of this chapter and on 3.2 we must no longer warn about things introduced with 3.1.
=> remove info here no longer or not needed at all

adoc/advanced_topics_image_management.adoc, book-to-set/MAIN-manager.xml
Kiwi OS image building will be enabled by default with:
https://github.com/SUSE/spacewalk/pull/5905
With this PR we remove from the manual the section to explain how to enable the feature.
Related issue:
https://github.com/SUSE/spacewalk/issues/5802
=> Docs: Kiwi OS Image building will be enabled by default

adoc/entities.adoc
In our context, smt != rmt (on version 12 you can continue using smt).
The others are probably obvious.
We probably also want it in maint/3.2.
=> fix entity defs

adoc/reference-webui-systems.adoc
According to https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/#tables you need the 'a' signifier in the cols attribute to say that there's asciidoc content in the column. From there, you need to make sure that there's a line above and below each list.
=> Fixed table layout

adoc/public-cloud-setup.adoc
I found that the command /usr/bin/suma-storage had been removed from the proxy instances in version (3.1). For this reason I have removed references relating to this command and the proxy server type. I have also added the same tip found in the susemanager-advanced-topics guide for proxy setup. This may need some review and may be stated better.
=> fix proxy storage for public cloud

adoc/quickstart3_chap_suma_keys_and_first_client.adoc
clarification about the difference when using the bootstrap script for
Salt clients. Keep the option enabled (what's the default).
=> Bootstrap using Salt option for Salt clients

adoc/quickstart3_chap_suma_keys_and_first_client.adoc
* Bootstrap using Salt option for Salt clients
clarification about the difference when using the bootstrap script for
Salt clients. Keep the option enabled (what's the default).
Enable 'Remote Commands' is mandatory.
=> Bootstrap using Salt option for Salt clients (#246)

adoc/retail_migr_chap_slepostosuma.adoc
swap step order in branch server installation procedure as proposed by @nadvornik ; otherwise empty profile usage would not be correct.
=> 1-by-1 branch server install and empty profile usage

adoc/quickstart3_chap_suma_keys_and_first_client.adoc
In the context of the GS, this info is superfluous.  In a positive
way, it is already provided in the "1.2.4 Network Requirements" section.
When approved, we can also submit it to maint/3.2
=> Delete general warning about network configuration

adoc/command-line-tools.adoc
The "mgr-sync enable-scc" subcommand is not available anymore.
We removed it and the docs should reflect this.
Even 3.1 and 3.2 does not have it anymore.
=> enable-scc subcommand is not available anymore

adoc/reference-webui-channels.adoc
When deleting a channel, channel was being removed correctly from database but in case of minion, channel was still assigned to the system. With this PR, we schedule salt state to update the minion as well.
=> Schedule a channel state for minions if an assigned channel to them is deleted.

adoc/advanced_topics_image_management.adoc
Correction: OS image building is exclusively supported on SLES12, including service packs (i.e. not SLES15)
*Suggestions for better wording are welcome* :smiley:
=> Correct the supported OS for OS image build hosts

adoc/retail_chap_formulas.adoc, adoc/retail_chap_install.adoc
Due to upcoming changes in code, vsftp will no longer be optional part.
Explicitely state that for working retail config, all formulas must be
properly configured.
=> Do not mark vsftp formula as an optional one

adoc/mgr_product_comparison.adoc
In [this bug report](https://bugzilla.suse.com/show_bug.cgi?id=1124013) we are asked about the reason why `spacecmd`'s `system_syncpackages` does not work with minions.
The reason is that the core of this functionality is not yet ported to Salt.
=> 2.1 comparison: clarify profile syncing support

modules/administration/nav-administration-guide.adoc, modules/administration/pages/channel-management.adoc, modules/architecture/pages/spacewalk-repo-sync.adoc, modules/client-configuration/nav-client-config-guide.adoc, modules/client-configuration/pages/channels.adoc
(This relates to https://bugzilla.novell.com/show_bug.cgi?id=1124634 but is broader than just that bug.)
* Added Channels section to client config, cribbed from reference-webui-channels.adoc, with reference to Admin Guide
* Added Channels section to Admin Guide, with outline for the section, and content from BZ1124634
Todo:
=> Channels sections in Client Cfg & Admin

adoc/bp_chap_expanded_support.adoc
This PR removes the section about adding the repository gpg key for Ubuntu minions.
This got automated here: https://github.com/SUSE/spacewalk/pull/7161
~~However: This PR should not be merged until the Ubuntu repositories are signed by the correct key~~
=> Removed Ubuntu trust gpg key sections

modules/client-configuration/pages/clients-ubuntu.adoc
Remove Ubuntu trust GPG key instructions, which are handled automatically by SUSE Manager
=> Remove Ubuntu trust GPG key section

adoc/quickstart3_chap_suma_keys_and_first_client.adoc, adoc/reference-webui-admin.adoc, adoc/reference-webui-salt.adoc
Mounting /tmp with noexec —see
https://github.com/SUSE/spacewalk/issues/7248
=> new section about Troubleshooting Salt Clients

modules/installation/pages/install-vm.adoc
https://bugzilla.suse.com/show_bug.cgi?id=1131374
https://github.com/SUSE/spacewalk/issues/7492
Removed disk size requirements from VM chap, refer to reqs chap instead.
=> Fix req's discrepancy in install guide 

modules/installation/pages/general-requirements.adoc
Required for Beta3.
Does not apply to Uyuni.
=> No registration code required for SLE15SP1 and SUSE Manager 4.0

branding/pdf-resources/entities.adoc, suma-site.yml, uyuni-site.yml
Required for Beta3:
This is adjusting versioning, as we still have 3.2 and SLE12 SP3 and salt 2018.03.0.
=> Fix versions for SLE/openSUSE/salt

modules/client-configuration/pages/clients-ubuntu.adoc
How to bootstrap an Ubuntu minion using `mgr-create-bootstrap-repo`.
=> Bootstrapping Ubuntu minions

modules/administration/nav-administration-guide.adoc, modules/administration/pages/tshoot-diskspace.adoc
I removed a section about reclaiming disk space from the zsystems chapter in the install guide (https://github.com/SUSE/doc-susemanager/pull/435), which would fit better in the Admin Guide. Will need some tidying up yet.
=> Added new troubleshooting section for reclaiming disk space

modules/client-configuration/pages/creating-activation-keys.adoc
Adding some notes on bandwitdh usage during registration depending on the Activation Key.
General context: https://github.com/SUSE/spacewalk/wiki/Proxy-NG-research
=> Add notes about bandwidth usage at registration time

adoc/reference-webui-systems.adoc
See https://github.com/SUSE/spacewalk/pull/7714
It is a backport of https://github.com/SUSE/doc-susemanager/pull/438 for SUSE Manager 3.2
=> Minion id is visible in System Info box

modules/installation/pages/client-requirements.adoc, suma-site.yml, uyuni-site.yml
Unless I am wrong, SUSE Manager 4.0 will support:
- openSUSE Leap 15.1
- Ubuntu 16.04
- Ubuntu 18.04
only as salt clients.
Maybe this section should have alternatives for Uyuni, as there we support Leap 42.3 as well, and CentOS6 and 7, but not RHEL6/7.
=> Add Leap 15.1, Ubuntu 16.04 and 18.04 as supported salt clients

modules/administration/pages/auth-methods.adoc
Add documentation for the Single Sign-On authentication mechanism.
Targeting Manager-4.0 RC and Uyuni.
PR enabling the functionality: https://github.com/uyuni-project/uyuni/pull/944
Fixes https://github.com/SUSE/spacewalk/issues/7732
=> Docs: add Single Sign-On documentation

modules/administration/pages/virtualization.adoc
Tell that the virtualization features will only work if the salt minion has 2019.2.0+ salt
=> Virtualization: mention the minimum salt version

adoc/bp_chap_salt_minion_onboarding_scaleability.adoc
"Backport" to 3.2 of relevant information from https://github.com/SUSE/doc-susemanager/pull/445
@keichwa @jcayouette If we've missed the deadline to get this to @juliogonzalez for the 3.2 package, we will at least need to update the online docs ASAP.
cc @moio
=> Salt rate limiting 3.2

modules/reference/pages/systems/system-details/sd-virtualization.adoc
https://github.com/SUSE/spacewalk/issues/7541
https://github.com/SUSE/doc-susemanager/pull/344
> This PR got caught up in the IA lift 'n' shift. The documentation for the AT Guide/Client Cfg has been completed, we are waiting for the appropriate section in the Reference Guide to be migrated, so that that content can also be replicated (ping @jcayouette).
=> Reference Guide component from PR#344

modules/administration/pages/tuning-largedeploys.adoc
Suggestion emerged as part of the resolution of the following SUSE Manager bugs:
https://bugzilla.suse.com/show_bug.cgi?id=1135075#c3
https://bugzilla.suse.com/show_bug.cgi?id=1135025
In essence, this jobs ran for hours/exhausted RAM while users were not interested in respective features, so it's best to just recommend disabling them.
=> Tuning: suggest disabling non-essential Taskomatic jobs

modules/client-configuration/pages/clients-ubuntu.adoc
Use `spacewalk-common-channels` as an alternative to manually creating Ubuntu repos and channels.
=> Add spacewalk-common-channels to Ubuntu client config

modules/reference/pages/navigation/categories-and-pages.adoc
Remove `Main Menu` placeholder.
The problem:
=> Remove wrong label

modules/client-configuration/pages/clients-ubuntu.adoc
`spacewalk-common-channels` is part of the `spacewalk-utils` package. The support status for this packages needs to be clarified.
Until it gets clarified disable the section about using `spacewalk-common-channels` with Ubuntu.
=> Disable section about using spacewalk-common-channels with Ubuntu

modules/administration/pages/virtualization.adoc, modules/installation/pages/ports.adoc
The VM Graphical Console feature requires the port 8050 to be reachable from the browser. Document this.
Port of #538.
=> 4.0 - Document 8050 port opening

modules/administration/pages/virtualization.adoc, modules/installation/pages/ports.adoc
The VM Graphical Console feature requires the port 8050 to be reachable from the browser. Document this.
=> Port 8050 needs to be opened for graphical console display

modules/administration/pages/virtualization.adoc
We need to mention that a restart of a minion is needed in order to make virtualization fully work.
We were restarting automatically but that can cause some other issues. Related PR which change that behavior is https://github.com/SUSE/spacewalk/pull/8083
=> Minion needs to be restarted after bootstrap

modules/client-configuration/pages/contact-methods.adoc
I think we agreed to use \<NAME\> or \<name\> where
```
[replaceable]``name``
```
is not possible.
=> some syntax fixes and fix complex ssh commands

modules/administration/nav-administration-guide.adoc, modules/administration/pages/vhm-file.adoc, modules/administration/pages/vhm-vmware.adoc, modules/administration/pages/virtual-hosts.adoc, modules/reference/pages/systems/virtual-host-managers.adoc
https://bugzilla.suse.com/show_bug.cgi?id=1139931
https://github.com/SUSE/spacewalk/issues/8239
This resolves the bug, but there's some follow up work to be done:
=> VHM content moved out of Reference, into Admin

modules/salt/pages/salt-terminology.adoc
https://github.com/SUSE/spacewalk/issues/8275
https://bugzilla.suse.com/show_bug.cgi?id=1140758
Customer has requested a note about suma not supporting "multiple Salt environments". I've assumed they're referring to this type of environment: https://docs.saltstack.com/en/latest/ref/states/top.html#environments and added a note accordingly.
@mcalmer can you please confirm my understanding here?
=> Added admon about multiple Salt environments.

modules/ROOT/pages/release-notes-version-4.0.adoc
They do not add anything useful anymore and can only mislead the reader into thinking the current version of SUSE Manager / Uyuni is not ready for production.
This kind of warnings should only be in the very version where they are relevant, and be removed in the next version.
=> Please remove warning notes for prerelease versions

modules/administration/pages/iss.adoc
This PR fixes an issue on the "Inter Server Sync (ISS)" documentation.
After setting the Master and Slave servers properly, the `mgr-inter-sync` command needs to be executed on the **slave** server and not in the **master** as documentation says.
This is a port of https://github.com/uyuni-project/uyuni-docs/pull/3
=> Fix issue on ISS doc: "mgr-inter-sync" needs to run on the slave

modules/administration/pages/tshoot-osadjabberd.adoc
Engineering notes were copied from the Wiki but are meant to be internal for our engineers, should not really be relevant for users.
Part of https://github.com/SUSE/spacewalk/issues/5217
=> Remove internal notes

modules/salt/pages/salt-states.adoc
For some reason currently we use the incorrect pillar names `rpm_download_point_XXX` instead of `pkg_download_point_XXX`.
See the original PR for 4.0: https://github.com/SUSE/doc-susemanager/pull/366/files#diff-8bf787463eb899039a59878b8b2ce800R179
For 3.2: https://github.com/SUSE/doc-susemanager/pull/375/files#diff-ba2328059d5e5a16c5dcbdff39701c1fR473
This is just a find/replace, maybe we should also check if any other edits were lost in the process.
=> Use correct pillar name

modules/reference/pages/systems/system-details/sd-remote-command.adoc
https://github.com/SUSE/spacewalk/issues/5554
Removed the incorrect image in latest. I don't think it's worth backporting this.
=> Ref guide: Remove wrong image

modules/client-configuration/pages/clients-ubuntu.adoc
For IP reasons, add note about Canonical not supporting or endorsing SUSE Manager. We should have had that since the very beginning:
https://ubuntu.com/legal/intellectual-property-policy
Also, make a bit more straightforward the first part of the page.
=> Add Canonical IP safeguard

modules/reference/pages/command-line-tools.adoc
Info about logging taken from the manpage.
@mcalmer does it make sense this way?  The previous version looked like a cut-and-paste error to me.
=> mgr-sync logging

modules/upgrade/nav-upgrade-guide.adoc
somehow forgotten or lost since earlier this year.
Here is an old changelog entry:
commit cb32b96147d28db5a0d7b0913c82ded1c2185ef1
Author: Karl Eichwalder <ke@suse.de>
Date:   Thu May 23 12:49:52 2019 +0200
new section about migrating 3.2 servers to 4 (#467)
=> add migrate-3x-4x.adoc to the nav (2 times)

modules/upgrade/pages/migrate-3x-4x.adoc
Hubert, do you think it makes sense to restructure this chapter this way?  I'd like to have the 'mgr-setup -r' step part of the "normal" migration procedure, just optionally.
=> make systemdata copying an optionally substep of the migration

modules/client-configuration/pages/clients-and-activation-keys.adoc
The button for creating an Activation Key is "Create Activation Key" instead of "Update Activation Key".
=> Update the button name for creating an AK in clients-and-activation-keys.adoc

modules/administration/pages/iss.adoc
fixes for minor errors encountered during the review.
TODO after merging: check that the FQDNs (`server1.example.com`) are **not** rendered as links. This was the case before and it was wrong:
=> Technical review: Admin guide: Inter Server Sync

modules/client-configuration/pages/registration-webui.adoc
This page is also in good condition. It was just missing a line about the proxy field in case, the user wants to register the system against it.
=> Registration: add a line for registering against the proxy

modules/salt/pages/large-scale-tuning.adoc
This PR changes the default value for max memory of taskomatic to 4GB
=> Change the default value for taskomatic to 4GB

modules/client-configuration/pages/clients-ubuntu.adoc
- Manual procedure for SUSE Manager (`spacewalk-common-channels` not supported yet)
- "Automated" procedure for Uyuni
- Fix the `if`s, now SUSE Manager goes first, Uyuni second, and the `if`s only happen for the content that is really different.
Feel free to edit directly at the PR for minor stuff. Reserve the comments only for doubts or big stuff.
=> WIP: Ubuntu rework

modules/salt/nav-salt-guide.adoc, modules/salt/pages/salt-command.adoc, modules/salt/pages/salt-example-formula.adoc, modules/salt/pages/salt-intro.adoc, modules/salt/pages/salt-states.adoc, modules/salt/pages/salt-useful-commands.adoc
This PR suggests some changes into the Salt guide after reviewing some of the Salt pages:
- Avoid using "Salt Calls" to prevent confusion with `salt-call` command line tool. This page has been renamed to "Salt Command"
- Rename "Salt Commands" to "Salt Useful Commands" to avoid duplicity.
- Minor adjustments on different pages
Tracker: https://github.com/SUSE/spacewalk/issues/9296
=> Review of Salt guide (Round 1)

branding/pdf/entities.adoc, modules/client-configuration/nav-client-config-guide.adoc, modules/client-configuration/pages/clients-centos.adoc, modules/client-configuration/pages/clients-rh.adoc, modules/client-configuration/pages/clients-sleses.adoc, suma-site.yml, uyuni-site.yml
General rework. Among other things:
- New `clients-sleses.adoc` for SUSE Linux Enterprise Server with Expanded Support (AKA RES, AKA Red Hat Expanded Support).
- `clients-rh.adoc` now discribes the procedure for real RHEL clients, with including how to connect the server to the CDN. The clients to be used are those for Expanded Support Client Tools for SUSE Manager, or Uyuni Client Tools for Uyuni (uses an `if`)
- `clients-centos.adoc` now describes how to onboard CentOS with Expanded Support Client Tools for SUSE Manager, or with Uyuni Client Tools for Uyuni (uses an `if`)
**IMPORTANT**: The CentOS part is NOT valid for 3.2 unless we backport changes for spacewalk-common-channels there.
I added `if` where needed so we can show the correct warnings for either SUSE Manager on Uyuni.
This …
=> WIP: Rework ES/RHEL/CentOS doc

modules/salt/pages/salt-terminology.adoc
This should be `grains.items` instead of `grains.ls`.
=> Fix for grains typo

modules/installation/pages/hardware-requirements.adoc
With this PR, we provided a recommended value for swap space. I wasn't sure if some more explanation should be added here.
https://github.com/SUSE/spacewalk/issues/9821
=> Swap space recommendation

modules/client-configuration/nav-client-config-guide.adoc, modules/client-configuration/pages/supported-features-debian.adoc, modules/client-configuration/pages/supported-features-es.adoc, modules/client-configuration/pages/supported-features-rh.adoc, modules/client-configuration/pages/supported-features-sles.adoc, modules/client-configuration/pages/supported-features.adoc, suma-site.yml, uyuni-site.yml
I felt a bit confused when navigating the split feature matrix, so I tried to reorganize it in a way that feels easier to navigate to me:
- Move supported features under 'Supported clients and features' (from each client's subsection)
- Split SLES from the generic 'Supported clients and features' main page, for consistency with the other clients
- Split SLES ES from RHEL supported features page, as ES has its own client configuration page
- Some clarifications in the CentOS features page to make it clear what happens when you have ES and what happens when you do not
- Ubuntu: more recent version first (like the others) and change some "not supported" features to question marks, as they will be supported in the future
- Hide RHEL/SLES ES 8, as it is not (yet) supported (it will be in …
=> Reorganize feature matrix

modules/client-configuration/pages/supported-features.adoc
We don't support CentOS 7 x86. I probably introduced this mistake by copy & pasting.
=> No CentOS 7 i386

modules/installation/pages/ports.adoc
Since uyuni-project/uyuni#1579 and SUSE/spacewalk#10044 the client doesn't need access to port 8050 on the server.
=> Port 8050 no longer needs to be opened

modules/client-configuration/pages/vhm-caasp.adoc
Adds information on how to register CaaSP nodes into SUSE Manager/Uyuni.
Fixes https://github.com/SUSE/spacewalk/issues/9961
=> Docs: add CaaSP information for onboarding clients

modules/retail/nav-retail.adoc, modules/retail/pages/retail-formulas-intro.adoc, modules/retail/pages/retail-install-setup.adoc, modules/retail/pages/retail-install-unified.adoc
* Add new retail formulas content and rework retail setup
* Fix non-working links in retail install
- two links in retail install were missing .adoc suffix
* Add saltboot diagram to the Terminal ops as a boot process
https://github.com/SUSE/spacewalk/issues/9297
=> Rework retail environment setup and formulas pages

modules/administration/nav-administration-guide.adoc, modules/administration/pages/live-patching-channel-setup.adoc, modules/administration/pages/live-patching-sles12.adoc, modules/administration/pages/live-patching-sles15.adoc
Split out spacewalk-manage-channel-lifecycle into an own Setup Chapter and change the order a bit.
The idea:
1st prepare the channels for Live Patching either with CLM (prefered) or with spacewalk-manage-channel-lifecycle tool.
2nd assign the clients to the clones and prepare the system for Live Patching.
=> rework live patching

modules/client-configuration/pages/vhm-caasp.adoc
As part of the merged RFC for forbidden CaaSP operations, this PR defines the operations that should not be done on a CaaSP node registered to Uyuni/SUSE Manager.
Ref: https://github.com/uyuni-project/uyuni-rfc/pull/26
=> Docs: update unsupported CaaSP operations
