xml/public-cloud-setup.xml
* Update ec2metadata call to retrieve the public IP address
* Add section how to handle interrupted susemanager_setup call
* prefix hwinfo call with sudo because this is required
=> Update SUMA in the public cloud article

xml/public-cloud-setup.xml
- General revisions to emphasis need to run in a VPC
- Provide information about how to use on demand instances
=> Additional changes

xml/public-cloud-setup.xml
=> - Additional clarifications for SUMa 3 in the Public Cloud w.r.t.

xml/public-cloud-setup.xml
Try to make the hostname change more clear
=> Be more clear on the hostname update

xml/bp_chap_lifecycle_management.xml
...by adding missing `role` attribute.
=> Fix the epub build

xml/public-cloud-setup.xml
=> - Provide a better explanation concerning registration of insatnces with

xml/advanced_topics_optimizing_apache_tomcat.xml
This is to explain better the database connection formula, as I believe the parameters in it were not really explained elsewhere.
@jcayouette can you take a look at the DocBook formatting? :smile:
=> Explain the database connection formula

xml/advanced_topics_proxy_quickstart.xml
This would need to be reviewed by someone with more SUSE manager
experience than me...
=> Added more details about proxy configuration.

xml/advanced_topics_proxy_quickstart.xml
- fixed one typo
- used a `<replaceable>` for where there was a variable
- added instructions for bootstrapping from web ui
=> Fixed proxy instructions

xml/advanced_topics_ports.xml
https://github.com/SUSE/spacewalk/issues/2293
=> separate list for internal server ports;

adoc/reference-webui-systems.adoc
=> In Virtualization, the 2nd subtab is now called Provisioning

adoc/reference-webui-systems.adoc
=> Groups menu belongs in front of the Virtualization menu

adoc/reference-webui-systems.adoc
https://github.com/SUSE/spacewalk/issues/3992
=> Ke channel assignment pages #3992

adoc/advanced_topics_image_management.adoc, adoc/reference-webui-images.adoc
Hide Kiwi documentation using `draft`
=> Feat: hide Kiwi documentation

xml/reference-webui-systems.xml
I think we also want this back-ported in maint/3.1
https://github.com/SUSE/doc-susemanager/pull/83
=> clarify that manual creation of the file is not supported #83

adoc/reference-webui-intro.adoc
adoc refinement; see https://github.com/SUSE/spacewalk/issues/4643
=> adoc refinement

adoc/reference-webui-configuration.adoc
https://github.com/SUSE/spacewalk/issues/4643
=> Ke adoc refinement reference configuration

adoc/reference-webui-systems.adoc
=> Ke adoc refinement reference systems

adoc/bp_chap_getting_started_with_salt_formulas.adoc, adoc/reference-webui-systems-autoinstallation.adoc
=> Ke adoc refine autoinstallation

adoc/advanced_topics_suma3_zsystems.adoc
https://github.com/SUSE/spacewalk/issues/5086
This removes the entities and cleans up the heading until we can take a closer look at fixing them.
=> Issue #5086: Remove entities in heading

adoc/bp_chap_expanded_support.adoc
Fixing comment in https://github.com/SUSE/doc-susemanager/pull/108#discussion_r198023450
=> fixed error in command

adoc/advanced_topics_cobbler.adoc
From https://wiki.microfocus.com/index.php/SUSE_Manager/NewFeatures2.1/BareMetalProvisioning
=> Issue #498: new AT bare metal provisioning section

adoc/public-cloud-setup.adoc
From https://wiki.microfocus.com/index.php/SUSE_Manager/Register_Clones
=> Issue #4998: adding procedure for registering cloned systems

adoc/bp_chap_troubleshooting.adoc, adoc/entities.adoc
Fixing comment from https://github.com/SUSE/doc-susemanager/pull/107
=> update version string

adoc/command-line-tools.adoc
=> Issue #4896 Adding mgr-create-bootstrap-repo command and --flush option to AT

adoc/advanced_topics_spacecmd_command_guide.adoc
From https://wiki.microfocus.com/index.php/SUSE_Manager/Spacecmd
=> Issue #4998: adding additional troubleshooting spacecmd sub-section

adoc/command-line-tools.adoc
From https://wiki.microfocus.com/index.php/SUSE_Manager/Rotating_spacewalk-repo-sync_log
=> Issue #4998: add note about log rotation for reposync

adoc/advanced_topics_security.adoc
Add doc for how to enable signing metadata.
=> Develop sign metadata

adoc/bp_chap_systems_management.adoc
from https://wiki.microfocus.com/index.php/SUSE_Manager/NewFeatures2.1/PackageEULA
=> Issue #5073 Add note about reviewing EULA

adoc/quickstart3_chap_suma_keys_and_first_client.adoc
From https://wiki.microfocus.com/index.php/SUSE_Manager/SaltClientfromTemplate
This content exists in long-form in BP Troubleshooting. Added a note and a cross-reference to the GS, in the registering a salt minion category. 
@jcayouette Please check my cross reference code :)
=> Issue #5073: add cloned salt info and xref to GS

adoc/bp_chap_expanded_support.adoc
white-space issues and tag usage
use rhel entity
=> adoc refinement - expanded support chapter

adoc/bp_chap_expanded_support.adoc
fix spacewalk-repo-sync command - https://github.com/SUSE/spacewalk/issues/5226
=> RES 7 has a different filesystem structure

adoc/public-cloud-setup.adoc
https://github.com/SUSE/spacewalk/issues/5124
=> Issue #5124: fixing format errors

adoc/bp_chap_suma_backup.adoc
**WIP**
https://github.com/SUSE/spacewalk/issues/5215
Reorganised section, added concept info. Still needs a cold backup procedure (waiting on SME @mcalmer), and probably some more troubleshooting.
=> Issue #5215: redo smdba backup info

adoc/bp_chap_suma_backup.adoc
https://github.com/SUSE/spacewalk/issues/5215
This completes the actual backup section, and technically fulfills the request. Second half of the chapter still needs work, though.
=> Issue #5215: smdba updates

adoc/bp_client_migration.adoc, adoc/bp_sp_migration.adoc
https://github.com/SUSE/spacewalk/issues/5055
Remove reference, and a couple of super minor formatting issues I noticed.
=> Issue #5055: remove reference to upgrading from 2.1

adoc/quickstart3_chap_suma_keys_and_first_client.adoc
https://wiki.microfocus.com/index.php/SUSE_Manager/NewFeatures2.1/PackageLock
=> Issue #5073: Add package locking section

adoc/bp_chap_suma_backup.adoc
From feedback:
* updated list of files
* made recovery into a procedure
=> [WIP] Issue #5215: smdba updates

adoc/bp_chap_getting_started_with_salt_formulas.adoc
This depends on https://github.com/SUSE/spacewalk/pull/5290
Also, I added a fix that makes the documentation consistent with the code, see https://github.com/SUSE/spacewalk/issues/4581
=> updated doc for visibleIf tag

adoc/quickstart3_chap_suma_keys_and_first_client.adoc
=> fix ifdef error

adoc/advanced_topics_cobbler.adoc
https://github.com/SUSE/spacewalk/issues/5292
=> remove xinetd

adoc/quickstart3_chap_install_overview.adoc
=> fixed markup error in adoc

adoc/bp_client_migration.adoc, adoc/bp_ex_autoinst_system-upgrade.adoc, adoc/entities.adoc
I completely replaced 11 to 12 upgrade; it's pretty similar to the 12 to 15 upgrade (I could add a note, if wanted).
I also have to add a tip about "modules".
I still must check the autoyast example file.
=> describe upgrade 12 > 15; plus layout/markup fixes

adoc/bp_chap_config_management_with_salt.adoc
https://wiki.microfocus.com/index.php/SUSE_Manager/SystemGroupStates
=> Added group states info

adoc/bp_chap_systems_management.adoc
https://github.com/SUSE/spacewalk/issues/5335
Also reworked this section to make the info flow a little better.
=> Added troubleshooting info

adoc/quickstart3_chap_suma_keys_and_first_client.adoc
https://github.com/SUSE/spacewalk/issues/5335
And some editing of the first para in the section.
=> Switch clients from traditional to salt

adoc/advanced_topics_proxy_quickstart.adoc
Update documentation to reflect changes made as part of this card https://github.com/SUSE/spacewalk/issues/5303
=> Proxies can also be minions now (FATE#323069)

adoc/quickstart3_chap_suma_keys_and_first_client.adoc
https://wiki.microfocus.com/index.php/SUSE_Manager/System_Activation_Keys
https://github.com/SUSE/spacewalk/issues/5335
=> Added activation key best practices.

adoc/bp_postgresql_database_migration.adoc, adoc/bp_sec_mgr_21_migration.adoc, adoc/bp_sp_migration.adoc
* Added in non-backup related content from https://wiki.microfocus.com/index.php/SUSE_Manager/DB_FAQ per https://github.com/SUSE/spacewalk/issues/5335
* Commented out duplicate info in migration chapter (happy to argue about the best way to manage this)
* Reorganised and re-worded content
=> reorganised postgres chapter

DC-retail-getting-started, Makefile, adoc/book_retail_getting_started.adoc, adoc/entities.adoc, adoc/retail_chap_admin.adoc, adoc/retail_chap_components.adoc, adoc/retail_chap_install.adoc, adoc/retail_chap_introduction.adoc, adoc/retail_chap_next.adoc
Creates the directory structure for each chapter, with major headings.
=> Initial Chapter Structure

adoc/advanced_topics_virtualization.adoc, adoc/reference-webui-systems.adoc
This PR documents uyuni-project/uyuni#5
An update of image ``system_details_traditional_virtualization_details.png``
=> virtualiazation documentation update

adoc/retail_chap_admin.adoc
=> fix UI labels and other widget names

adoc/quickstart3_chap_suma_installation_jeos.adoc
addressing https://github.com/SUSE/spacewalk/issues/5021
=> more or less cosmetic jeos fixes 

adoc/retail_chap_install.adoc
https://github.com/SUSE/spacewalk/issues/5471
=> Ke retail branch inst

adoc/retail_chap_introduction.adoc
Let's avoid "Introduction" with an "Introduction" section ;)
=> what do you think about [abstract]?

adoc/quickstart3_chap_suma_setup_with_yast.adoc
https://github.com/SUSE/spacewalk/issues/5782
https://bugzilla.suse.com/show_bug.cgi?id=1105497
=> do not install 3rd party software

adoc/retail_chap_admin.adoc
https://github.com/SUSE/spacewalk/issues/5615
=> Admin chapter, mass terminal config.

adoc/retail_chap_admin.adoc
Updated hardware type instruction in Admin chapter, per https://github.com/SUSE/spacewalk/issues/5613
=> Admin chapter

adoc/bp_client_migration.adoc, adoc/reference-webui-systems-autoinstallation.adoc
https://github.com/SUSE/spacewalk/issues/5373
=> Auto-Installing Salt Minions Currently Not Supported

adoc/advanced_topics_spacecmd_command_guide.adoc
use macros
add -c/--config option
=> more or less cosmetic updates

adoc/retail_chap_install.adoc
Instead of patterns-suma_proxy recommend patterns-suma_retail_proxy for
installation.
better layout for clarity (one action per item).
=> patterns-suma_retail_proxy and one action/item

adoc/retail_chap_components.adoc
minor simplifications, feel free to change or refuse.
=> simplifications

adoc/retail_chap_admin.adoc
With new information from @nadvornik https://github.com/SUSE/spacewalk/issues/5615
=> Updated mass terminal config

adoc/quickstart3_chap_suma_keys_and_first_client.adoc
https://github.com/SUSE/spacewalk/issues/5546
=> both way sync with maintenance/3.2

adoc/quickstart3_chap_suma_keys_and_first_client.adoc
https://github.com/SUSE/spacewalk/issues/5546
=> both way sync with develop

adoc/bp_chap_activation_key_management.adoc, adoc/quickstart3_chap_suma_keys_and_first_client.adoc
adoc refinement.  Once accepted push it to maintenance/3.2, too.
=> Ke adoc bp activ

adoc/retail_chap_install.adoc
https://github.com/SUSE/spacewalk/issues/5935
=> Updated instructions to config branch server

adoc/quickstart3_chap_suma_setup_with_yast.adoc
https://github.com/SUSE/spacewalk/issues/5978
https://bugzilla.suse.com/show_bug.cgi?id=1109906
=> Added pw criteria

adoc/bp_chap_suma_backup.adoc
=> Removed reference to "db-check" 

xml/bp_chap_activation_key_management.xml
=> WIP: backport from develop

adoc/advanced_topics_spacecmd_command_guide.adoc
https://github.com/SUSE/spacewalk/issues/6016
=> spacecmd caching

adoc/retail_chap_components.adoc, adoc/retail_chap_install.adoc, adoc/retail_chap_introduction.adoc
=> Technical review feedback

adoc/retail_chap_admin.adoc, adoc/retail_chap_install.adoc
Updated procedure headings to fix titles (again)
=> Procedure headings

adoc/retail_chap_components.adoc, adoc/retail_chap_install.adoc
https://github.com/SUSE/spacewalk/issues/6072
=> adds missing system group info

adoc/retail_chap_admin.adoc, adoc/retail_chap_install.adoc
Image synchronization is required part of installing new branch server and also day-to-day operations. This PR adds this info in various relevant places.
=> Add image sync information

xml/advanced_topics_proxy_quickstart.xml, xml/bp_client_migration.xml, xml/quickstart3_chap_install_overview.xml, xml/reference-webui-systems.xml
https://github.com/SUSE/spacewalk/issues/5717
=> SLE 12 SP4 supported as a client system

xml/bp_chap_expanded_support.xml, xml/quickstart3_chap_suma_keys_and_first_client.xml
mgr-create-bootstrap-repo options
https://github.com/SUSE/spacewalk/issues/6187
Does it make sense this way?
=> Ke maint31 bootstrap repo

adoc/retail_chap_admin.adoc
Per https://github.com/SUSE/spacewalk/issues/6068
=> Note to check UI after registering a terminal

adoc/retail_chap_admin.adoc
https://github.com/SUSE/spacewalk/issues/6210
https://bugzilla.novell.com/show_bug.cgi?id=1111521
=> Add note about conflicting settings in YAML file

xml/advanced_topics_proxy_quickstart.xml, xml/quickstart3_chap_install_overview.xml, xml/quickstart3_chap_suma_installation_sles12_sp1.xml, xml/susemanager-decl.ent
More version info (sle 12 SP4) wanted.
https://github.com/SUSE/spacewalk/issues/5717 now done.
=> Ke maint31 sp4 version info

xml/bp_sp_migration.xml, xml/quickstart3_chap_install_overview.xml, xml/reference-intro.xml
more about SLE 12 SP4 as a 3.1 Base OS.
https://github.com/SUSE/spacewalk/issues/5717
mc, can please check whether it ok this way.  I tried to address this issue in a general way (there does not seem a major difference compared with SP3 if you think about user visible changes).
=> Ke maint31 server mirgration sp4

adoc/retail_migr_chap_slepostosuma.adoc
separate complete and one-by-one migration
and some minor changes (version numbers, etc. ;) )
=> Ke migration feedback jiri vlad

adoc/retail_chap_admin.adoc, adoc/retail_chap_install.adoc, adoc/retail_migr_chap_slepostosuma.adoc
As Vladimir recommended, make it clear at more places that a suse manager proxy server is the base for a branch server.
mention the activation key driven registration more often (bootstrap script).
=> Ke retail branch proxy

adoc/retail_migr_chap_slepostosuma.adoc
#271 (resolve vladimir's feedback) @nadvornik
=> branch server: install clarification

adoc/quickstart3_chap_install_overview.adoc
just for completeness ...  Once approved it should go into 3.2, too
=> mention Salt section

adoc/retail_chap_install.adoc, adoc/retail_chap_introduction.adoc
https://github.com/SUSE/spacewalk/issues/6440
=> Changed xrefs to hard links.

adoc/quickstart3_chap_suma_keys_and_first_client.adoc, adoc/reference-webui-systems.adoc
https://github.com/SUSE/spacewalk/issues/6326
=> registering salt clients: use Configuration File Deployment

adoc/reference-webui-intro.adoc, adoc/reference-webui-systems.adoc
https://github.com/SUSE/spacewalk/issues/6118
when accepted, back-port to 3.2
=> package search: rebuild index first

adoc/reference-webui-overview.adoc
https://github.com/SUSE/doc-susemanager/issues/256
https://github.com/SUSE/spacewalk/issues/6439
back-port to 3.2 when approved.
=> configure notification lifetime

adoc/quickstart3_chap_suma_keys_and_first_client.adoc
https://github.com/SUSE/spacewalk/issues/6445
=> Updated wording, added info about checking repo.

adoc/quickstart3_chap_install_overview.adoc
https://github.com/SUSE/doc-susemanager/issues/241
=> Updated hw reqs to 4+ cores

adoc/advanced_topics_virtualization.adoc, adoc/bp_chap_systems_management.adoc, adoc/reference-webui-admin.adoc, adoc/reference-webui-systems.adoc
https://github.com/SUSE/doc-susemanager/issues/50
=> Removed references to up2date

adoc/book_mgr_getting_started.adoc, adoc/book_retail_getting_started.adoc, adoc/book_retail_migration.adoc, adoc/book_suma_reference_manual.adoc
https://github.com/SUSE/doc-susemanager/issues/262
=> Included common legal notice for all books that didn't have it.

adoc/retail_chap_admin.adoc
https://github.com/SUSE/doc-susemanager/issues/243
=> Updated content around hwtype group

adoc/reference-webui-systems.adoc
https://github.com/SUSE/spacewalk/issues/6387
https://bugzilla.suse.com/show_bug.cgi?id=1116864&GoAheadAndLogIn=1
=> BZ 1116864 - Updates to Systems > VHMs section.

adoc/bp_chap_getting_started_with_salt_formulas.adoc
https://github.com/SUSE/spacewalk/issues/6607
=> Minor updates to custom formula metadata info

adoc/bp_chap_getting_started_with_salt_formulas.adoc
=> improve intro on forms

adoc/quickstart3_chap_suma_keys_and_first_client.adoc
https://github.com/SUSE/spacewalk/issues/6626
Added admonitions about GPG keys in bootstrapping, and general edits.
=> GPG keys and bootstrapping

adoc/advanced_topics_proxy_quickstart.adoc
https://github.com/SUSE/spacewalk/issues/6581
https://bugzilla.suse.com/show_bug.cgi?id=1118667
=> Change Proxy to Server

adoc/reference-webui-overview.adoc
Add documentation for the PR: https://github.com/uyuni-project/uyuni/pull/329
To be backported to 3.2 and 3.1 as soon as approved.
=> Add documentation for the new notifications property java.notifications_type_disabled

adoc/reference-webui-overview.adoc
Backport of https://github.com/SUSE/doc-susemanager/pull/306
=> 3.2 - Add documentation for the new notifications property java.notifications_type_disabled

adoc/quickstart3_chap_suma_salt_gs.adoc
https://bugzilla.suse.com/show_bug.cgi?id=1117497
https://github.com/SUSE/spacewalk/issues/6587
=> Updated external links to saltstack docs

adoc/advanced_topics_optimization_scalability.adoc
Addresses bug https://bugzilla.suse.com/show_bug.cgi?id=1117119, downstream issue https://github.com/SUSE/spacewalk/issues/6434
=> Scalability: add rhn-search maximum memory knob

Makefile, adoc/advanced_topics_virtualization.adoc, adoc/reference-webui-systems.adoc
Documentation for uyuni-project/uyuni#181
May need some more details and a few screenshots
=> Virt create

adoc/advanced_topics_cobbler.adoc
https://github.com/SUSE/spacewalk/issues/6688
https://bugzilla.suse.com/show_bug.cgi?id=1120112
=> Added specific note about port that Cobbler uses.

adoc/quickstart3_chap_suma_salt_gs.adoc
Ref https://github.com/SUSE/doc-susemanager/pull/307
=> Update per feedback

adoc/advanced_topics_proxy_quickstart.adoc
https://github.com/SUSE/spacewalk/issues/6604
when approved to be back-ported to 3.2
=> ke-bsc-1102884-proxy-cert

xml/reference-webui-overview.xml
https://github.com/SUSE/doc-susemanager/pull/306
=> notification settings

adoc/advanced_topics_image_management.adoc, adoc/retail_chap_admin.adoc, adoc/retail_chap_components.adoc
https://github.com/SUSE/spacewalk/issues/6633
=> RAM requirements for hosts running OS images built with Kiwi

adoc/advanced_topics_proxy_quickstart.adoc
https://github.com/SUSE/spacewalk/issues/6729
=> proxy migration from trad to salt not possible

adoc/bp_chap_getting_started_with_salt_formulas.adoc
https://github.com/SUSE/spacewalk/issues/6512
and @mvidner, please review.
=> Ke git 6512 forms features

adoc/retail_salt_formulas.adoc
https://github.com/SUSE/spacewalk/issues/6640
https://bugzilla.suse.com/show_bug.cgi?id=1119807
=> Add admonition about saltboot parameter conflict.

adoc/advanced_topics_image_management.adoc
=> Correct the supported OS for OS image build hosts

adoc/bp_chap_troubleshooting.adoc
from 2.1 docs.
https://github.com/SUSE/spacewalk/issues/6596
=> add Gathering information with "spacewalk-report"

adoc/reference-webui-systems.adoc
https://github.com/SUSE/spacewalk/issues/4802
=> salt-config-channel reference

adoc/retail_chap_admin.adoc, adoc/retail_chap_install.adoc
reported in BZ#1122251 & BZ#1122900
=> Fix dead links in Retail GSG

xml/mgr_product_comparison.xml
=> 2.1 comparison: clarify profile syncing support (Manager 3.1 branch)

adoc/bp_chap_expanded_support.adoc, adoc/entities.adoc
https://github.com/SUSE/spacewalk/issues/6978
Needs to be backported to 3.2, and added to Client Config Guide for 4.0.
=> Add Ubuntu information

adoc/retail_chap_admin.adoc
avoid sentences too long
change wording for clarity (hopefully)
=> improve wording

adoc/advanced_topics_optimization_scalability.adoc
Context: https://bugzilla.suse.com/show_bug.cgi?id=1109853#c16
@Loquacity: please take care that this change is also ported to develop.
I hope the form is OK - please decide if a box is sufficient or if we should introduce the parameter earlier in the paragraph.
=> Add feedback collected during resolution of bsc#1109853

docs/modules/installation/pages/general-requirements.adoc
https://github.com/SUSE/spacewalk/issues/6917
Adding to the new 4.0 docs, as this section has already been moved.
=> Added note about supported browsers

docs/modules/ROOT/pages/release-notes-version-4.0.adoc
=> Edit Docs Release Notes (replaces PR#351)

modules/administration/pages/virtualization.adoc
https://github.com/SUSE/doc-susemanager/pull/344
This is for the portion of the PR that was intended for the AT Guide, which is now in the Admin Guide.
=> Replicating PR#344 - AT portion

modules/installation/pages/install-proxy.adoc
SUSE/spacewalk#7055
https://bugzilla.suse.com/show_bug.cgi?id=1125153
This PR replaces #349
=> Adding note about pre-reqs

modules/reference/pages/admin/reference-webui-admin.adoc
https://github.com/SUSE/spacewalk/issues/6571
Replacing https://github.com/SUSE/doc-susemanager/pull/346
=> add menu:minion-action-cleanup-default

modules/installation/pages/proxy/install-proxy.adoc
SUSE/spacewalk#6874
https://bugzilla.suse.com/1122780
This replaces #354
=> Replaces #354

modules/client-configuration/nav-client-config-guide.adoc, modules/client-configuration/pages/clients-ubuntu.adoc
For the beta1 docs.
https://github.com/SUSE/doc-susemanager/pull/343
=> Add Ubuntu Client section now that it's been released.

modules/installation/pages/install-server-setup.adoc
https://github.com/SUSE/spacewalk/issues/6968
https://github.com/SUSE/spacewalk/issues/4424
=> Removed SCC credentials step from YaST install.

modules/salt/pages/salt-formulas.adoc
start documenting https://github.com/SUSE/spacewalk/issues/3608
=> edit-group with nesting

modules/salt/pages/salt-states.adoc
https://github.com/SUSE/doc-susemanager/issues/331
https://github.com/SUSE/spacewalk/issues/6890
=> RPM endpoint salt pillars

modules/retail/pages/retail-formulas.adoc
https://github.com/SUSE/spacewalk/issues/7171
=> Add image sync formula

adoc/bp_chap_expanded_support.adoc
Reverts SUSE/doc-susemanager#348
=> Revert "Removed Ubuntu trust gpg key sections"

modules/administration/pages/security.adoc
https://github.com/SUSE/spacewalk/issues/5907
=> Adding mirroring source packages section

adoc/quickstart3_chap_suma_salt_gs.adoc
"backport" of https://github.com/SUSE/doc-susemanager/pull/366
=> Adding package endpoint salt pillar content to 3.2

adoc/advanced_topics_proxy_quickstart.adoc
fix formatting of the list; add missing info
https://github.com/SUSE/spacewalk/issues/7080
=> minor cleanup configure-proxy.sh

modules/client-configuration/nav-client-config-guide.adoc, modules/client-configuration/pages/system-management.adoc, modules/client-configuration/pages/using-ssm.adoc
Building out System Management section, and adding SSM info
https://github.com/SUSE/spacewalk/issues/7224
https://bugzilla.suse.com/show_bug.cgi?id=1128098
=> Client Cfg - System Management & SSM

modules/architecture/pages/taskomatic.adoc, modules/reference/pages/systems/systems-list.adoc
Add documentation regarding 'MinionCheckin' taskomatic job
=> Add documentation regarding 'MinionCheckin' taskomatic job

modules/client-configuration/pages/manual-registration/salt-registration.adoc, modules/reference/pages/salt/salt-remote-commands.adoc
https://github.com/SUSE/spacewalk/issues/7248
=> salt: /tmp and noexec

adoc/bp_chap_suma_backup.adoc
improve 'Restore from a Manual Backup
https://github.com/SUSE/spacewalk/issues/7417
https://bugzilla.suse.com/show_bug.cgi?id=1129764
=> Ke manual restore #7417

adoc/bp_chap_suma_backup.adoc
tiny tweak, also related to https://github.com/SUSE/spacewalk/issues/7417
=> Ke manual backup 2 #7417

adoc/bp_chap_suma_backup.adoc
https://github.com/SUSE/spacewalk/issues/7441
@isbm, IIRC, your are the expert with smdba.  Can you please help with reviewing?  It's enough if you'd review the smdba related change!
=> Ke smdba #7441

modules/administration/pages/backup-restore.adoc
forward port from maint/3.2: https://github.com/SUSE/doc-susemanager/pull/387
cf. https://github.com/SUSE/spacewalk/issues/7417
=> Restore from a Manual Backup #7417

modules/administration/nav-administration-guide.adoc, modules/administration/pages/content-lifecycle.adoc, modules/client-configuration/nav-client-config-guide.adoc, modules/client-configuration/pages/content-lifecycle.adoc
https://github.com/SUSE/spacewalk/issues/7467
=> Content Lifecycle

modules/administration/pages/repo-metadata.adoc
From https://github.com/SUSE/doc-susemanager/pull/355
@mateiw
=> Add docs about mgr-sign-metadata-ctl

modules/administration/pages/backup-restore.adoc
https://github.com/SUSE/spacewalk/issues/7441
This is basically a forward port of  SUSE/doc-susemanager#391
=> smdba sections need update

adoc/bp_live_patching.adoc
=> BZ1131691 - Best Practices bad link

modules/retail/pages/retail-formulas.adoc, modules/retail/pages/retail-install.adoc
=> BZ1131695 - Bad link in Retail book

modules/client-configuration/pages/clients-ubuntu.adoc
Follow up on @mateiw  https://github.com/SUSE/doc-susemanager/pull/409
=> Ubuntu  Clients - Structure Editing.

adoc/bp_chap_expanded_support.adoc
"backporting" changes from https://github.com/SUSE/doc-susemanager/pull/417 to 3.2
=> Ubuntu Clients - Structure Editing

modules/retail/pages/retail-formulas.adoc
https://github.com/SUSE/spacewalk/issues/7524
https://bugzilla.suse.com/1131701
=> BZ1131701 updating bind formula procedure

modules/installation/pages/general-requirements.adoc
https://github.com/SUSE/spacewalk/issues/5133
=> SUSE Manager doesn't come with LTSS

Makefile
is this what's needed?
If wanted I can change it.
=> prep antora.yml for suma or uyuni

Makefile, antora.yml, suma-site.yml, uyuni-site.yml
Adjusted build variables for both SUMA and UYUNI outputs. This means we no longer have to fiddle with these before selecting a target.
TODO: We need to adjust antora.yml at build time depending on the productname_uyuni or productname_suma.
=> updated makefile for uyuni/suma targets

antora.yml, modules/installation/nav-installation-guide.adoc, modules/installation/pages/server-setup.adoc, suma-site.yml, uyuni-site.yml
Fixed those pesky build errors in the Install Guide, and updated *-site.yml to point to master
=> Fix build errors

modules/administration/pages/tshoot-packages.adoc
https://github.com/SUSE/spacewalk/issues/7502
=> Add note about package locks.

adoc/reference-webui-systems.adoc
https://github.com/SUSE/spacewalk/issues/7592
bsc#1131867
=> Manage System Completely via SSH now fully supported

modules/installation/pages/proxy-setup.adoc
https://github.com/SUSE/spacewalk/issues/7517
https://bugzilla.suse.com/show_bug.cgi?id=1131679
=> BZ#1131679 - Updated path for proxy config

modules/retail/pages/retail-admin.adoc
https://github.com/SUSE/spacewalk/issues/7552
=> create group; bsc#1131977

modules/retail/nav-retail.adoc, modules/retail/pages/retail-delta-images.adoc
https://github.com/SUSE/spacewalk/issues/7039
@Loquacity please decide where we want to add this.
=> New on Using Delta Images

modules/installation/pages/hardware-requirements.adoc, modules/retail/pages/retail-requirements.adoc
https://bugzilla.suse.com/show_bug.cgi?id=1132254
https://github.com/SUSE/spacewalk/issues/7590
=> Updated disk space reqs for RH products

modules/retail/pages/retail-formulas.adoc
https://bugzilla.suse.com/show_bug.cgi?id=1131877
https://github.com/SUSE/spacewalk/issues/7600
=> Changed example IP for branch server to 192.168.1.5

modules/reference/pages/configuration/files-locally-managed.adoc
https://bugzilla.suse.com/show_bug.cgi?id=1132569
https://github.com/SUSE/spacewalk/issues/7646
=> mgrcfg-manager is for clients

modules/reference/pages/systems/system-details.adoc
See https://github.com/uyuni-project/uyuni/pull/883
=> Minion id is visible in System Info box

modules/retail/pages/retail-formulas.adoc
https://bugzilla.suse.com/show_bug.cgi?id=1132082
https://github.com/SUSE/spacewalk/issues/7556
=> VsFTPd Formula update

modules/administration/nav-administration-guide.adoc, modules/administration/pages/iss.adoc, modules/reference/pages/admin/iss-configuration.adoc, modules/reference/pages/admin/iss-master-setup.adoc, modules/reference/pages/admin/iss-slave-setup.adoc
Adds ISS info to Admin Guide.
Still  TODO:
Relevant docs bugs:
https://bugzilla.suse.com/show_bug.cgi?id=1131813
https://bugzilla.suse.com/show_bug.cgi?id=1132089
Associated Issues:
https://github.com/SUSE/spacewalk/issues/7570
https://github.com/SUSE/spacewalk/issues/7571
=> ISS Content

modules/client-configuration/nav-client-config-guide.adoc, modules/client-configuration/pages/bootstrapping-clients.adoc, modules/client-configuration/pages/channels.adoc, modules/client-configuration/pages/client-config-overview.adoc, modules/client-configuration/pages/client-proxy.adoc, modules/client-configuration/pages/clients-and-activation-keys.adoc, modules/client-configuration/pages/clients-and-scc.adoc, modules/client-configuration/pages/creating-activation-keys.adoc, modules/client-configuration/pages/non-suse-clients.adoc, modules/client-configuration/pages/registration-webui.adoc, modules/client-configuration/pages/salt-client-proxy.adoc, modules/client-configuration/pages/scale-minions.adoc, modules/client-configuration/pages/script-client-proxy.adoc, modules/client-configuration/pages/traditional-vs-salt.adoc
https://github.com/SUSE/spacewalk/issues/7711
Following on from https://github.com/SUSE/doc-susemanager/pull/444 @moio
=> Edits to Client Cfg Guide

modules/retail/pages/retail-admin.adoc
https://github.com/SUSE/spacewalk/issues/7553
https://bugzilla.suse.com/show_bug.cgi?id=1131979
=> power on terminals after data registration

modules/ROOT/pages/release-notes-version-4.0.adoc
=> Adding Retail to relnotes

modules/administration/nav-administration-guide.adoc, modules/administration/pages/autoyast-example.adoc, modules/administration/pages/virtualization.adoc
enable and improve autoyast example profile.
=> Admin autoyast example channel #7740

modules/retail/pages/retail-formulas.adoc
https://github.com/SUSE/spacewalk/issues/7450
=> pxe saltboot params

modules/retail/pages/retail-install-setup.adoc
https://github.com/SUSE/spacewalk/issues/7597
=> call salt on the suma server

modules/administration/pages/tuning-largedeploys.adoc
I think "to compromise" is not the right verb here.
=> Tuning: word fix

adoc/advanced_topics_optimization_scalability.adoc
"backport" of https://github.com/SUSE/doc-susemanager/pull/466
=> Large Install Tuning - Taskomatic jobs

modules/client-configuration/pages/registration-bootstrap.adoc
https://github.com/SUSE/spacewalk/issues/7838
https://bugzilla.suse.com/show_bug.cgi?id=1133936
=> Add note about Python pre-req for bootstrap

modules/installation/pages/install-proxy-unified.adoc
proxy install intro: change wording for clarity
=> proxy install intro: change wording for clarity

modules/salt/pages/salt-rate-limiting.adoc
https://github.com/SUSE/spacewalk/issues/7731
=> Disable Salt Mine

modules/reference/pages/systems/system-details/sd-software-channels.adoc
This might need to go into the relnotes, too.
https://github.com/SUSE/spacewalk/issues/7774
=> Added admonition about beta packages

modules/administration/pages/tshoot-osadjabberd.adoc, modules/reference/pages/admin/iss-slave-setup.adoc
https://github.com/SUSE/spacewalk/issues/7901
=> fix random bad adoc

modules/upgrade/nav-upgrade-guide.adoc
https://github.com/SUSE/spacewalk/issues/7901
=> Missing Content - Upgrade Guide

modules/administration/pages/prometheus.adoc
Minor edits to clean up after the merge on Friday.
=> Minor edits to the new Prometheus section

modules/client-configuration/pages/cobbler.adoc
https://bugzilla.suse.com/show_bug.cgi?id=1136611
Follow up in https://github.com/SUSE/spacewalk/issues/7964
=> Unsupported Cobbler bits

modules/administration/pages/prometheus.adoc
Per: https://github.com/SUSE/doc-susemanager/pull/462#issuecomment-497447200
=> Add uyuni/suma example grafana dashboard

modules/salt/pages/salt-rate-limiting.adoc
Updates per feedback on https://github.com/SUSE/doc-susemanager/pull/474
=> Salt Mine edits

modules/administration/nav-administration-guide.adoc, modules/administration/pages/public-cloud.adoc
From https://www.suse.com/documentation/suse-manager-3/3.2/susemanager-advanced-topics/html/book.suma.advanced.topics/book.suma.advanced.topics.html  went missing in the lift and shift
=> Add content on Public Cloud

modules/reference/pages/help/api-faq.adoc, modules/reference/pages/help/api-menu.adoc, modules/reference/pages/help/api-overview.adoc, modules/reference/pages/help/api-sample-scripts.adoc, modules/reference/pages/help/documentation-version.adoc, modules/reference/pages/help/release-notes.adoc, modules/reference/pages/intro.adoc, modules/reference/pages/systems/autoinst-profile-details.adoc
https://github.com/SUSE/spacewalk/issues/7901
=> Missing Content - Ref Guide

modules/administration/nav-administration-guide.adoc
https://github.com/SUSE/spacewalk/issues/7901
=> Missing Content - Admin Guide

modules/reference/pages/software/manage-channels.adoc
Add a section to explain how comps file are processed when a channel is
composed by multiple repositories.
Re: http://mailman.suse.de/mlarch/SuSE/galaxy-devel/2019/galaxy-devel.2019.05/msg00122.html
=> Docs: explain how comps file are processed

adoc/quickstart3_chap_suma_salt_gs.adoc
https://github.com/SUSE/doc-susemanager/pull/474
https://github.com/SUSE/doc-susemanager/pull/492
=> "Backport" of content re: Disabling the Salt Mine

modules/installation/nav-installation-guide.adoc, modules/installation/pages/hardware-requirements.adoc, modules/installation/pages/network-requirements.adoc, modules/installation/pages/proxy-setup.adoc, modules/installation/pages/server-setup.adoc
Fixing xref in the installation module
=> Install cleanup xref ke

modules/upgrade/pages/proxy-migration.adoc
=> $redhat_management_server gets replaced automatically

modules/reference/pages/navigation/left-navigation-bar.adoc
https://github.com/SUSE/spacewalk/issues/7766
=> update left nav bar

modules/client-configuration/pages/clients-ubuntu.adoc
From https://github.com/SUSE/doc-susemanager/pull/513
=> Add spacewalk-common-channels to Ubuntu client config 

modules/administration/pages/auth-methods.adoc
https://github.com/SUSE/doc-susemanager/issues/522
=> Fix procedure adoc

modules/administration/pages/prometheus.adoc
As long as we do not know how we can ship it, we should not have it in the docs
=> Remove Grafana from Monitoring Chapter

modules/administration/pages/content-lifecycle.adoc
Remove preview notice, comment out unfinished procedure.
=> Content Lifecycle Management - remove tech preview

modules/administration/pages/virtual-hosts.adoc
https://bugzilla.suse.com/show_bug.cgi?id=1136561
https://github.com/SUSE/spacewalk/issues/8023
=> Add admonition about SSL certs trust.

modules/administration/pages/autoyast-example.adoc, modules/reference/pages/images/images-image-list.adoc, modules/reference/pages/systems/activation-keys.adoc, modules/reference/pages/systems/advanced-search.adoc, modules/reference/pages/systems/autoinst-distributions.adoc, modules/reference/pages/systems/autoinst-file-preservation.adoc, modules/reference/pages/systems/autoinst-overview.adoc, modules/reference/pages/systems/autoinst-profile-details.adoc, modules/reference/pages/systems/autoinst-profiles.adoc, modules/reference/pages/systems/custom-system-info.adoc, modules/reference/pages/systems/ssm-overview.adoc, modules/reference/pages/systems/system-details.adoc, modules/reference/pages/systems/system-details/sd-audit.adoc, modules/reference/pages/systems/system-details/sd-configuration.adoc, modules/reference/pages/systems/system-details/sd-formulas.adoc, modules/reference/pages/systems/system-details/sd-groups.adoc, modules/reference/pages/systems/system-details/sd-packages.adoc, modules/reference/pages/systems/system-details/sd-patches.adoc, modules/reference/pages/systems/system-details/sd-properties.adoc, modules/reference/pages/systems/system-details/sd-provisioning.adoc, modules/reference/pages/systems/system-details/sd-remote-command.adoc, modules/reference/pages/systems/system-groups.adoc, modules/reference/pages/systems/systems-list.adoc, modules/reference/pages/systems/virtual-host-managers.adoc, modules/reference/pages/users/active-users.adoc, modules/reference/pages/users/user-details.adoc, modules/reference/pages/users/users-menu.adoc
Following up on https://github.com/SUSE/doc-susemanager/pull/521
=> Updated xrefs to "for/see" format.

modules/administration/pages/content-lifecycle.adoc
... +  minor fixes of the existing sections.
Review commit-by-commit please.
=> Add a section about 'Using Content Lifecycle Project'

modules/client-configuration/pages/autoinstallation-methods.adoc
Question: What is the alternative to AutoYast/Kickstart for Salt minions? @moio?
=> Autoinstall Intro rewrite

modules/retail/pages/retail-formula-saltboot.adoc
@nadvornik PR is ready for review, please.
close https://github.com/SUSE/spacewalk/issues/7836
=> Saltboot parttype #7836 ke

modules/administration/pages/content-lifecycle.adoc
Follow up from https://github.com/SUSE/doc-susemanager/pull/535
Related to https://bugzilla.suse.com/show_bug.cgi?id=1137955 and https://github.com/SUSE/spacewalk/issues/8093
=> Edits to CLM section

modules/installation/nav-installation-guide.adoc, modules/installation/pages/install-vm.adoc
close https://github.com/SUSE/spacewalk/issues/8027
=> Jeos vm #8027 ke

modules/retail/pages/_partials/entities.adoc, modules/retail/pages/retail-admin.adoc, modules/retail/pages/retail-install-packages.adoc, modules/retail/pages/retail-install-setup.adoc, modules/retail/pages/retail-introduction.adoc, modules/retail/pages/retail-migration-slepostosuma.adoc, modules/retail/pages/retail-next.adoc, modules/retail/pages/retail-requirements.adoc
https://github.com/SUSE/spacewalk/issues/7810
@nadvornik
=> adjust version numbers

modules/administration/nav-administration-guide.adoc, modules/administration/pages/tuning-changelogs.adoc
https://github.com/SUSE/spacewalk/issues/7090
=> Add Tuning info about changelog metadata storage.

modules/ROOT/pages/release-notes-version-4.0.adoc
Remove fixed known issues, remove TBD email, add instructions to report an issue.
=> Update doc relnotes

modules/retail/pages/retail-install-setup.adoc, modules/retail/pages/retail-install-unified.adoc
https://github.com/SUSE/spacewalk/issues/8211
=> Install Edits

modules/administration/pages/public-cloud.adoc, modules/administration/pages/tshoot-registerclones.adoc, modules/administration/pages/virtualization.adoc, modules/architecture/pages/rhnsd.adoc, modules/architecture/pages/traditional-osad.adoc, modules/architecture/pages/traditional-rhnsd.adoc, modules/client-configuration/pages/contact-methods.adoc, modules/reference/pages/audit/audit-openscap-overview.adoc, modules/reference/pages/patches/applying-patches.adoc, modules/reference/pages/systems/system-details/sd-hardware.adoc, modules/reference/pages/systems/system-details/sd-packages.adoc, modules/reference/pages/systems/system-details/sd-properties.adoc, modules/reference/pages/systems/systems-list.adoc
https://github.com/SUSE/spacewalk/issues/8149
=> Rhnsd #8149 ke

modules/administration/pages/virtualization.adoc, modules/client-configuration/pages/contact-methods.adoc
https://github.com/SUSE/spacewalk/issues/8229
=> info on rhnsd timer

adoc/advanced_topics_virtualization.adoc, adoc/bp_chap_systems_management.adoc, adoc/bp_chap_troubleshooting.adoc, adoc/manager_reference_openscap.adoc, adoc/public-cloud-setup.adoc, adoc/reference-webui-patches.adoc, adoc/reference-webui-systems.adoc
more less literal back-port from master (just different file names...).
https://github.com/SUSE/doc-susemanager/pull/552
https://github.com/SUSE/doc-susemanager/pull/562
=> Rhnsd timer #8264

branding/supplemental-ui/suma-susecom/css/site-extra.css, branding/supplemental-ui/suma-susecom/partials/header-content.hbs
Fix: https://github.com/SUSE/doc-susemanager/issues/567
=> Fix header bar content: do not overlaps element on small screen

modules/administration/pages/tuning-changelogs.adoc
Edits per feedback from @mcalmer on https://github.com/SUSE/doc-susemanager/pull/551
=> Edit Tuning info about changelog metadata storage. 

modules/client-configuration/pages/disconnected-setup.adoc
https://github.com/SUSE/spacewalk/issues/8358
=> Removed entities from headings

adoc/bp_live_patching.adoc
https://github.com/SUSE/spacewalk/issues/8579
https://bugzilla.suse.com/show_bug.cgi?id=1096426
=> fix command line error

modules/administration/pages/live-patching-sles12.adoc, modules/administration/pages/live-patching-sles15.adoc
SUSE/spacewalk#8579
https://bugzilla.suse.com/show_bug.cgi?id=1096426
=> Keichwa patch 2

modules/retail/nav-retail.adoc, modules/retail/pages/retail-components.adoc, modules/retail/pages/retail-deploy-terminals.adoc, modules/retail/pages/retail-install-setup.adoc, modules/retail/pages/retail-install-unified.adoc, modules/retail/pages/retail-introduction.adoc, modules/retail/pages/retail-migration-slepostosuma.adoc, modules/retail/pages/retail-next.adoc
=> 3.2/4.0 version issues

modules/installation/nav-installation-guide.adoc
Include bootstrap procedure https://github.com/SUSE/spacewalk/issues/8369
=> enable proxy registration

modules/installation/pages/client-requirements.adoc
https://bugzilla.suse.com/show_bug.cgi?id=1137898
https://github.com/SUSE/spacewalk/issues/8113
=> Added SLES for SAP

modules/installation/pages/general-requirements.adoc
=> Supported browsers

modules/retail/pages/retail-components.adoc
https://github.com/SUSE/spacewalk/issues/8315
=> Add uefi boot

adoc/bp_chap_salt_minion_onboarding_scaleability.adoc
https://github.com/SUSE/doc-susemanager/pull/603
=> LimitNOFILE backport

modules/administration/nav-administration-guide.adoc, modules/administration/pages/monitoring.adoc
* Added service discovery info (from @cavalheiro )
* Renamed file to Monitoring 
Still to come:
* More details on the steps required (waiting on @juliogonzalez )
https://github.com/SUSE/spacewalk/issues/8330
https://bugzilla.suse.com/show_bug.cgi?id=1137345
=> Monitoring Updates

adoc/reference-webui-admin.adoc
=> backport from https://github.com/SUSE/doc-susemanager/pull/609

modules/client-configuration/pages/clients-ubuntu.adoc
Confirmed by @cbbayburt to be working.
=> Use the correct channel names for Ubuntu when using Uyuni

modules/administration/pages/public-cloud.adoc
https://github.com/SUSE/spacewalk/issues/8933
=> Public Cloud docs

adoc/bp_live_patching.adoc, adoc/entities.adoc
help with adoc tagging.  more than 1 menu: in a row can cause layout trouble.
=> cleanup adoc tagging

modules/administration/pages/mirror-sources.adoc
=> Admin mirror source content review10 #8361 ke

modules/installation/nav-installation-guide.adoc, modules/installation/pages/install-intro.adoc, modules/installation/pages/install-vm.adoc
https://github.com/SUSE/spacewalk/issues/8982
=> jeos installation (cleanup)

modules/salt/pages/salt-formulas.adoc
https://github.com/SUSE/spacewalk/issues/8914
=> CPU mitigations formula

modules/salt/pages/large-scale-tuning.adoc
Fixes a couple of broken links.
=> Tuning guide: fix xrefs

modules/salt/pages/large-scale-tuning.adoc
The original text was inaccurate.
=> Tuning: SUSE customers should contact Consulting

modules/installation/pages/install-proxy-unified.adoc, modules/installation/pages/install-server-unified.adoc
https://github.com/SUSE/spacewalk/issues/9042
=> Remove reference to 15.1

modules/installation/pages/hardware-requirements.adoc, suma-site.yml, uyuni-site.yml
https://github.com/SUSE/spacewalk/issues/9039
=> Fixed IBM Z entity render problem

modules/installation/pages/general-requirements.adoc
https://github.com/SUSE/spacewalk/issues/9038
=> Note about IE being unsupported

modules/installation/pages/server-setup.adoc
=> Add missing "to"

modules/client-configuration/pages/clients-and-activation-keys.adoc
This PR provides some minor fixes in some doc pages.
I've left `TODO` lines where I need some input. Please comment feedback on them so I'll update accordingly when they're all resolved.
=> Minor fixes for typos and syntax errors

modules/installation/pages/proxy-setup.adoc
Instead of presenting a security issue as a limitation, present it as a something good
=> Positive message

modules/installation/pages/proxy-registration.adoc
=> Add proper link text

modules/administration/nav-administration-guide.adoc, modules/administration/pages/public-cloud-azure.adoc, modules/administration/pages/public-cloud.adoc
Azure documentation.
Now we need better alignment with the general public cloud document.
=> Public cloud #8951 ke

modules/administration/pages/content-lifecycle.adoc, modules/reference/pages/clm/clm-filters.adoc
... + minor small fixes related to Content Lifecycle Manager.
=> Content Lifecycle Manager: Enhance the section about filters

modules/retail/pages/retail-components.adoc, modules/retail/pages/retail-deploy-terminals.adoc, modules/retail/pages/retail-install-setup.adoc, modules/retail/pages/retail-install-unified.adoc, modules/retail/pages/retail-install.adoc, modules/retail/pages/retail-requirements.adoc
https://github.com/SUSE/spacewalk/issues/8364
=> retail install sections cleanup

modules/retail/pages/retail-migration-intro.adoc, modules/retail/pages/retail-migration-slepostosuma.adoc, modules/retail/pages/retail-next.adoc, modules/retail/pages/retail-prepare-migration.adoc
https://github.com/SUSE/spacewalk/issues/8364
This covers migration/upgrade.
**We need sections on upgrading from 3.1 or 3.2 to 4.0!**
=> WIP: Retail upgrade cleanup 4 #8364 ke

modules/retail/pages/retail-deploy-terminals.adoc, modules/retail/pages/retail-formula-bind.adoc, modules/retail/pages/retail-formula-branchnetwork.adoc, modules/retail/pages/retail-formula-dhcpd.adoc, modules/retail/pages/retail-formula-pxe.adoc, modules/retail/pages/retail-formula-saltboot.adoc, modules/retail/pages/retail-formulas-intro.adoc
=> Retail cleanup 2 #8364 ke

modules/upgrade/nav-upgrade-guide.adoc, modules/upgrade/pages/client-migration.adoc, modules/upgrade/pages/db-migration.adoc, modules/upgrade/pages/migrate-3x-3x.adoc, modules/upgrade/pages/migrate-3x-4x.adoc, modules/upgrade/pages/performing-an-sp-migration.adoc, modules/upgrade/pages/proxy-migration.adoc, modules/upgrade/pages/server-upgrade.adoc, modules/upgrade/pages/sp-migration.adoc, modules/upgrade/pages/upgrade-overview.adoc, modules/upgrade/pages/upgrade-script-example.adoc
https://github.com/SUSE/spacewalk/issues/8366
=> Content Review: Upgrade Guide

modules/client-configuration/pages/clients-rh.adoc, modules/client-configuration/pages/creating-a-tools-repository.adoc, modules/installation/pages/server-setup.adoc
https://github.com/SUSE/spacewalk/issues/8955
=> replaced tailf with tail -f globally

modules/administration/nav-administration-guide.adoc
See https://github.com/SUSE/spacewalk/issues/8951
=> ATM, we do not want to publish the azure section

modules/reference/pages/command-line-tools.adoc, modules/reference/pages/configuration/config-files-menu.adoc
https://github.com/SUSE/spacewalk/issues/9127
https://bugzilla.suse.com/show_bug.cgi?id=1146411
=> improve Maximum Size for Configuration Files

modules/reference/pages/salt/salt-remote-commands.adoc
https://github.com/SUSE/spacewalk/issues/9128
https://bugzilla.suse.com/show_bug.cgi?id=1146443
=> you match salt clients by minion_id or with wildcards

modules/reference/pages/images/images-stores.adoc
Clarify a section about OS Image/Kiwi images stores.
=> Docs: clarify image store for Kiwi images

modules/upgrade/nav-upgrade-guide.adoc
https://github.com/SUSE/spacewalk/issues/9036
=> Removed 3.x to 3.x section

modules/installation/pages/install-vm.adoc
https://github.com/SUSE/spacewalk/issues/8363
Cleanup and addressing https://github.com/SUSE/spacewalk/issues/9043
=> Install cleanup jeos #8363 ke

modules/installation/pages/proxy-registration.adoc, modules/installation/pages/proxy-setup.adoc, modules/installation/pages/server-setup.adoc
Setup files, starting with proxy.
https://github.com/SUSE/spacewalk/issues/8363
=> Installation Guide: Setup files (server and proxy)

modules/installation/pages/install-proxy-unified.adoc
https://github.com/SUSE/spacewalk/issues/8363
=> proxy unified install

adoc/advanced_topics_proxy_quickstart.adoc
https://github.com/SUSE/spacewalk/issues/9178
https://bugzilla.suse.com/show_bug.cgi?id=1146895
=> add link to Bootstrap Script creation

modules/client-configuration/pages/client-config-overview.adoc
https://github.com/SUSE/spacewalk/issues/8304
=> Feature Matrix

modules/administration/nav-administration-guide.adoc, modules/administration/pages/maintenance-window.adoc, modules/upgrade/nav-upgrade-guide.adoc, modules/upgrade/pages/maintenance-window-tasks.adoc
https://github.com/SUSE/spacewalk/issues/8235
=> WIP: Add Maintenance Window Content

modules/upgrade/pages/db-migration.adoc, modules/upgrade/pages/migrate-3x-4x.adoc
https://github.com/SUSE/spacewalk/issues/9203
https://bugzilla.suse.com/show_bug.cgi?id=1148342
=> Upgrade postgres #9203 ke

modules/upgrade/nav-upgrade-guide.adoc, modules/upgrade/pages/migrate-3x-4x.adoc, modules/upgrade/pages/troubleshooting-upgrades-and-migrations.adoc, modules/upgrade/pages/troubleshooting.adoc
https://github.com/SUSE/spacewalk/issues/9154
=> Upgrade Guide - Troubleshooting

modules/installation/pages/general-requirements.adoc
https://github.com/SUSE/spacewalk/issues/9304
https://bugzilla.suse.com/show_bug.cgi?id=1148148
Edits per request. Upgraded admon from Note to Important.
=> Lifecycle admonition - Install Guide

modules/installation/pages/hardware-requirements.adoc, modules/installation/pages/install-proxy-unified.adoc
https://github.com/SUSE/spacewalk/issues/9291
=> Add Proxy hw reqs

modules/administration/pages/content-lifecycle.adoc
=> Fix formatting issue

modules/administration/pages/content-lifecycle.adoc
We have multiple "Matcher" which should be explained.
=> Add info about available Matcher algorithms

modules/installation/pages/general-requirements.adoc
See also here: https://github.com/SUSE/spacewalk/issues/9040#issuecomment-520800508
=> use https://download.suse.com/index.jsp as default download URL

modules/client-configuration/pages/cobbler.adoc
starting with https://github.com/SUSE/spacewalk/issues/7964
close https://github.com/SUSE/spacewalk/issues/7964
=> cobbler option fix

modules/administration/pages/mirror-sources.adoc
Just add the info what you need to run to get the sources synced.
=> minor update

modules/upgrade/pages/db-migration.adoc
also see https://github.com/SUSE/doc-susemanager/pull/712
=> re-using findings from 3.2 update: downtime / space

modules/administration/pages/content-lifecycle-examples.adoc, modules/administration/pages/content-lifecycle.adoc
We implemented some new filters and we had UI changes for the Filter setup.
This is now reflected in the docs as well
=> Update clm doc

adoc/bp_postgresql_database_migration.adoc
close https://github.com/SUSE/spacewalk/issues/8324
With minimal effort I tried to address the DB migration to postgresql 10 (that's needed if you want to update the underlying OS to SP4 (or SP5)).
Adding a dedicated section and some minor cosmetic changes.
=> Postgres10 #8324 ke

modules/upgrade/pages/db-migration.adoc
Here https://github.com/SUSE/doc-susemanager/pull/712 continues
=> port from maint/3.2

modules/administration/pages/master-fingerprint.adoc
Fixes https://github.com/SUSE/spacewalk/issues/9472
Upstream PR: https://github.com/saltstack/salt/pull/54699
=> Clarify salt master fingerprint instructions

modules/upgrade/nav-upgrade-guide.adoc
The PDF nav was out of date with the HTML nav.
=> Upgrade Guide - PDF nav fix

modules/upgrade/pages/client-migration.adoc
https://github.com/SUSE/spacewalk/issues/9153
=> remove sles12 upgrade instructions

modules/installation/nav-installation-guide.adoc, modules/installation/pages/pubcloud-requirements.adoc, modules/installation/pages/pubcloud-setup.adoc
https://github.com/SUSE/spacewalk/issues/8951
Follow up on https://github.com/SUSE/doc-susemanager/pull/666/
=> Install Guide - Add Public Cloud

modules/administration/nav-administration-guide.adoc, modules/administration/pages/space-management.adoc, modules/administration/pages/tshoot-diskspace.adoc
https://github.com/SUSE/spacewalk/issues/9457
=> Disk Space Checker

modules/reference/pages/systems/system-details/sd-properties.adoc
https://github.com/SUSE/spacewalk/issues/9519
=> Removed outdated image

modules/administration/pages/image-management.adoc
This PR contains a rework of Image Management: I clarified, added/moved/removed some sections.
=> Technical Review: Image Management

modules/retail/pages/retail-terminal-names.adoc
https://github.com/SUSE/spacewalk/issues/8843
=> Added terminal names content

modules/installation/pages/pubcloud-setup.adoc, modules/retail/pages/retail-terminal-names.adoc, modules/upgrade/pages/client-migration.adoc, modules/upgrade/pages/troubleshooting.adoc
Fixes:
`
asciidoctor: WARNING: pubcloud-setup.adoc: line 43: section title out of sequence: expected level 1, got level 2
`
`
asciidoctor: WARNING: client-migration.adoc: line 125: unterminated comment block
`
=> some minor build errors

modules/administration/pages/auth-methods.adoc
Adapted the authentication chapter of the admin guide.
=> Change admin auth

modules/client-configuration/pages/using-ssm.adoc
close https://github.com/SUSE/spacewalk/issues/9595
Thanks for your proposals, Ricardo.  Please review the PR.
=> wording changes per feedback

modules/administration/nav-administration-guide.adoc, modules/administration/pages/tshoot-osadjabberd.adoc
https://github.com/SUSE/spacewalk/issues/9516
=> Delink jabberd

modules/client-configuration/pages/contact-methods-osad.adoc, modules/client-configuration/pages/contact-methods-pushssh.adoc, modules/client-configuration/pages/contact-methods-rhnsd.adoc
https://github.com/SUSE/doc-susemanager/pull/774
PR#774 conflicted badly with the previously merged https://github.com/SUSE/doc-susemanager/pull/749
This PR replicates the wording changes of PR#774 on top of the structure merged in PR#749
=> Typos in Contact Methods

modules/administration/pages/kubernetes.adoc
Minor fixes for Kubernetes doc page as part of https://github.com/SUSE/spacewalk/issues/9295
=> Technical Review: Kubernetes

modules/administration/pages/tshoot-corruptrepo.adoc
https://github.com/SUSE/spacewalk/issues/9513
=> Technical Review: tshoot-corruptrepo.adoc

adoc/advanced_topics_proxy_quickstart.adoc
https://github.com/SUSE/doc-susemanager/pull/793
=> move country code tip to country code item

modules/administration/pages/maintenance-window.adoc, modules/upgrade/pages/db-migration.adoc, modules/upgrade/pages/migrate-4x-4x.adoc, modules/upgrade/pages/server-update.adoc, modules/upgrade/pages/upgrade-overview.adoc
addressing TR feedback by moio (SUSE/spacewalk#9512)
close SUSE/spacewalk#9512
close https://github.com/SUSE/doc-susemanager/pull/760
=> create clean maintenance window diff

modules/installation/pages/proxy-setup.adoc
https://github.com/SUSE/spacewalk/issues/9044
=> removed SLP ref

modules/salt/pages/salt-terminology.adoc
https://github.com/SUSE/spacewalk/issues/9597
=> Salt Guide: Remove Python version

modules/salt/pages/salt-terminology.adoc
https://github.com/SUSE/spacewalk/issues/9596
=> Alphabetize Salt terminology section

modules/installation/pages/general-requirements.adoc
https://bugzilla.suse.com/show_bug.cgi?id=1152735
=> Add partition permissions

modules/administration/pages/maintenance-window.adoc, modules/upgrade/pages/db-migration.adoc
per feedback, see
https://github.com/SUSE/doc-susemanager/pull/781#discussion_r332868061
=> maint window and upgrade

modules/administration/pages/monitoring.adoc
https://github.com/SUSE/spacewalk/issues/9413
=> Prometheus unsupported in non-routable networks

branding/pdf/entities.adoc, modules/administration/pages/kubernetes.adoc, suma-site.yml, uyuni-site.yml
https://github.com/SUSE/spacewalk/issues/9579
A lot of these procedures need more work, but I don't have access to a k8s cluster. 
Also: we will probably need to move this to the client config guide, but that can wait until we update the VHM/vmware section.
=> K8s line edit 

.vscode/settings.json, modules/administration/nav-administration-guide.adoc, modules/administration/pages/tshoot-packages.adoc, modules/administration/pages/tshoot-taskomatic.adoc
https://github.com/SUSE/spacewalk/issues/9517
split package tshoot section & update nav
=> Technical Review: tshoot-packages.adoc

modules/administration/pages/kubernetes.adoc, modules/administration/pages/tshoot-osadjabberd.adoc
=> fixes minor build problems

modules/administration/pages/image-management.adoc, modules/administration/pages/live-patching-sles12.adoc, modules/administration/pages/maintenance-window.adoc, modules/client-configuration/pages/autoyast.adoc, modules/client-configuration/pages/disconnected-setup.adoc, modules/client-configuration/pages/kickstart.adoc, modules/client-configuration/pages/virt-xenkvm.adoc, modules/installation/pages/install-ibmz.adoc, modules/installation/pages/install-server.adoc, modules/installation/pages/install-vm.adoc, modules/installation/pages/network-requirements.adoc, modules/reference/pages/help/api-overview.adoc, modules/reference/pages/systems/autoinst-distributions.adoc, modules/retail/pages/retail-admin.adoc, modules/retail/pages/retail-introduction.adoc, modules/retail/pages/retail-migration-slepostosuma.adoc, modules/retail/pages/retail-next.adoc, modules/salt/pages/large-scale-tuning.adoc, modules/salt/pages/salt-formulas-standard.adoc, modules/upgrade/pages/client-migration.adoc
Complete list in issue: https://github.com/SUSE/spacewalk/issues/9711
=> Update xrefs to docs site for new docs URL

modules/retail/pages/retail-migration-slepostosuma.adoc
https://github.com/SUSE/doc-susemanager/runs/261572477
=> b0rked xref

modules/client-configuration/pages/registration-bootstrap.adoc
Change the file name for the example file
=> Change the file name for the example file

modules/client-configuration/pages/channels.adoc
Change the menu reference to the Channels view
=> Change the menu reference to the Channels view

modules/ROOT/pages/index.adoc
https://github.com/SUSE/spacewalk/issues/9584
=> Added admon about most recent docs

modules/client-configuration/pages/autoinstallation-methods.adoc
https://github.com/SUSE/doc-susemanager/runs/274178828
=> fix broken xref

modules/upgrade/pages/db-migration.adoc
https://github.com/SUSE/spacewalk/issues/9733
=> Remove 3.2 refs from db upgrade

modules/salt/pages/salt-config-management.adoc
=> Fix: hide a comment

modules/salt/pages/salt-file-locations.adoc
Seems like we've got five file roots now. This also updates the config snippet.
=> Updated information for Salt File Locations and Structure

modules/administration/pages/monitoring.adoc
Syntax was broken and example did not work
=> monitoring: fix Prometheus configuration example

modules/administration/pages/tshoot-saltboot.adoc, modules/reference/pages/systems/system-details.adoc, modules/reference/pages/systems/system-details/sd-remote-command.adoc, modules/upgrade/pages/client-migration.adoc, modules/upgrade/pages/upgrade-script-example.adoc
https://github.com/SUSE/spacewalk/issues/9760
=> Update entities - {slea}->SLE

modules/administration/pages/disconnected-setup.adoc, modules/administration/pages/live-patching-sles12.adoc, modules/administration/pages/live-patching-sles15.adoc, modules/administration/pages/live-patching.adoc, modules/administration/pages/public-cloud.adoc, modules/administration/pages/tshoot-registerclones.adoc, modules/client-configuration/pages/creating-a-tools-repository.adoc, modules/client-configuration/pages/tshoot-clients.adoc, modules/client-configuration/pages/virt-xenkvm.adoc, modules/installation/pages/general-requirements.adoc, modules/installation/pages/install-ibmz.adoc, modules/installation/pages/install-intro.adoc, modules/retail/pages/retail-install-setup.adoc, modules/retail/pages/retail-install.adoc
https://github.com/SUSE/spacewalk/issues/9760
=> Update entities - {slsa}->SLES

branding/pdf/entities.adoc, modules/client-configuration/pages/clients-centos.adoc, modules/client-configuration/pages/clients-rh.adoc, modules/client-configuration/pages/clients-sleses.adoc, suma-site.yml
https://github.com/SUSE/spacewalk/issues/9760
=> Update entities - {slesesa}->{es}

modules/client-configuration/pages/client-automating-preparation.adoc
=> fixed heading level

modules/installation/nav-installation-guide.adoc, modules/installation/pages/network-requirements.adoc, modules/installation/pages/ports.adoc
https://github.com/SUSE/spacewalk/issues/9598
=> Update Ports in Install Guide

modules/salt/pages/salt-ssh.adoc
This image does not match style guide requirements. Will need to be reworked: https://github.com/SUSE/spacewalk/issues/9920
=> Remove image

modules/client-configuration/pages/clients-rh.adoc, modules/client-configuration/pages/supported-features.adoc
=> fixed missing entities

modules/client-configuration/pages/clients-and-activation-keys.adoc, modules/client-configuration/pages/registration-bootstrap.adoc, modules/client-configuration/pages/registration-overview.adoc, modules/client-configuration/pages/registration-webui.adoc
for activation keys and product/channel selection.
=> more xrefs

Makefile, modules/client-configuration/pages/registration-overview.adoc, suma-site.yml
- Added second workflow file for testing all feature branches
- Will always build off local branch during testing
- Tests all xrefs in the current branch
- Master branch is published to opensource.suse.com on push to master branch.
=> Testing ci final

modules/retail/pages/retail-requirements.adoc
- requirements updated from susemgr requirements
- switched place of branch and build host requirements
- fixed branch and build host table rendering
- removed the note about dhcp filtering, at the end doesn't make
much sense
=> Update retail hardware requirements

modules/administration/nav-administration-guide.adoc, modules/administration/pages/tshoot-logintimeout.adoc
=> web login timeout

modules/reference/pages/systems/system-details/sd-reactivation.adoc
=> fix rhnreg_ks call

modules/retail/pages/retail-offline.adoc
close https://github.com/SUSE/spacewalk/issues/9139
@aaannz it's ready for review!
https://github.com/SUSE/spacewalk/issues/9297
=> Enhancing Retail Offline Features

modules/installation/pages/ports.adoc
https://github.com/SUSE/spacewalk/issues/9890
=> Restructure port list

modules/client-configuration/nav-client-config-guide.adoc, uyuni-site.yml
=> uyuni build errors

modules/reference/pages/systems/system-details/sd-reactivation.adoc
https://bugzilla.suse.com/show_bug.cgi?id=1156526
https://github.com/SUSE/spacewalk/issues/10057
=> SD Reactivation - correction of command

branding/supplemental-ui/suma/suma-ghpages/partials/header-content.hbs
https://github.com/SUSE/spacewalk/issues/8351
=> un-german twitter link

modules/reference/pages/navigation/patch-alert-icons.adoc
https://github.com/SUSE/spacewalk/issues/8297
back-port to 4.0 wanted.
=> mention missing icons

modules/administration/pages/maintenance-window.adoc
https://github.com/SUSE/spacewalk/issues/9734
=> add monitoring server to maintenance window

modules/reference/pages/navigation/patch-alert-icons.adoc
back-port -- for more info, see https://github.com/SUSE/doc-susemanager/pull/895
=> mention missing icons (#895)

modules/client-configuration/pages/clients-ubuntu.adoc
https://github.com/SUSE/spacewalk/issues/9529
=> Ubuntu spacewalk-common-channels method

modules/installation/nav-installation-guide.adoc
by accident, I forgot that one here.
=> also disable install-server.adoc for the PDF

modules/administration/pages/content-lifecycle-examples.adoc, modules/administration/pages/content-lifecycle.adoc
This is a result of technical review reading: https://github.com/SUSE/spacewalk/issues/9295
=> Small fixes in Content Lifecycle section

modules/salt/pages/formulas-custom.adoc
Document changes introduced by https://github.com/uyuni-project/uyuni/pull/1527.
=> Update formula forms dev guide with new attributes
